#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CountZone_cLeon

#include "Basic.hpp"

#include "BP_CountZone_cLeon_classes.hpp"
#include "BP_CountZone_cLeon_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_CountZone_cLeon.BP_CountZone_cLeon_C.ExecuteUbergraph_BP_CountZone_cLeon
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CountZone_cLeon_C::ExecuteUbergraph_BP_CountZone_cLeon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CountZone_cLeon_C", "ExecuteUbergraph_BP_CountZone_cLeon");

	Params::BP_CountZone_cLeon_C_ExecuteUbergraph_BP_CountZone_cLeon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CountZone_cLeon.BP_CountZone_cLeon_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CountZone_cLeon_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CountZone_cLeon_C", "ReceiveTick");

	Params::BP_CountZone_cLeon_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
