#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameMode_cLeon

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_FirstPersonGameMode_V2_classes.hpp"
#include "EN_cLeonBodyType_structs.hpp"
#include "EN_cLeonGameMode_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GameMode_cLeon.BP_GameMode_cLeon_C
// 0x0088 (0x0448 - 0x03C0)
class ABP_GameMode_cLeon_C final : public ABP_FirstPersonGameMode_V2_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_GameMode_cLeon_C;                // 0x03C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABP_CountZone_cLeon_C*                  HunterCountZone;                                   // 0x03C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class ABP_CountZone_cLeon_C*                  SurvivorCountZone;                                 // 0x03D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	int32                                         StartWaitTimeDefault;                              // 0x03D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CurrentTimer;                                      // 0x03DC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         StartWaitTime;                                     // 0x03E0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3E4[0x4];                                      // 0x03E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_GameState_cLeon_C*                  BP_GameState_cLeon;                                // 0x03E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	int32                                         TimerDefault;                                      // 0x03F0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         MaxHunterNum;                                      // 0x03F4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_cLeonHunterLotteryArea_C*           LotteryArea;                                       // 0x03F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	int32                                         HunterWaitTimeDefault;                             // 0x0400(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         HunterWaitTime;                                    // 0x0404(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CheckAnswersTimeDefault;                           // 0x0408(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CheckAnswersTime;                                  // 0x040C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         GameModeIndex;                                     // 0x0410(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CanOpenOption;                                     // 0x0414(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_415[0x3];                                      // 0x0415(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        BodyChangeDelay;                                   // 0x0418(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TestInt;                                           // 0x0420(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CurrentGameMapIndex;                               // 0x0424(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CanModMap;                                         // 0x0428(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsModUse;                                          // 0x0429(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_42A[0x6];                                      // 0x042A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 SurvivorClass;                                     // 0x0430(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	int32                                         ChickenHunterWait;                                 // 0x0438(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ChickenMainSearch;                                 // 0x043C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ChickenAnswerTime;                                 // 0x0440(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BodyChange(EN_cLeonBodyType TargetBody, class ABP_PlayerController_cLeon_C* TargetController, const struct FTransform& OverrideSpawnTransform, bool KeepBody, bool BodyVisibility, class ABP_FirstPersonCharacter_cLeon_Character_C** CreateCharacter);
	void ChangeSpectateBody_Chicken_(bool KeepBody);
	void CheckAnswerTimeMinus();
	void ChickenSearchStop();
	void ChickenTeleport_BackHome();
	void ChickenTeleport_GotoMap();
	void ControllerArrayToPlayerState(TArray<class ABP_PlayerController_cLeon_C*>& PlayerController, TArray<class ABP_FirstPersonPlayerState_Online_cLeon_C*>* PlayerStateArray);
	void CountDownStart();
	void ExecuteUbergraph_BP_GameMode_cLeon(int32 EntryPoint);
	void GameEnd();
	void GameEndCheck();
	void GameStart();
	void GameStartWait();
	void GameStateCheck(bool* IsGameEnd, class FName* WinnerRole);
	void GameTimerClear();
	void GetCheckAnswersTime(int32* CheckAnswersTime_0);
	void GetChickenWinnerPlayer(class ABP_FirstPersonPlayerState_Online_cLeon_C** WinnerPlayerState);
	void GetDoubleWinnerPlayer(class ABP_FirstPersonCharacter_cLeon_Character_Hunter_C** WinnerPlayerActor);
	void GetGameModeIndex(int32* GameModeIndex_0);
	void GetGameTime(int32* TimerDefault_0);
	void GetHunterWaitTime(int32* HunterWaitTime_0);
	void GetMapIndex(int32* SelectMapIndex, class UBP_cLeonMapData_C** SelectMapDatas, int32* GameMapIndex, class UBP_cLeonMapData_C** GameMapDatas);
	void GetMaxBulletNum(int32* MaxBulletValue);
	void GetMaxHunterNum(int32* MaxHunterNum_0);
	void GetRandomLiveSurvivor(class ABP_FirstPersonCharacter_cLeon_Character_Survivor_C** SearchTargetSurvivor);
	void HunterWaitTimerMinus();
	void IsEndGame();
	void K2_OnLogout(class AController* ExitingController);
	void K2_OnRestartPlayer(class AController* NewPlayer);
	void K2_PostLogin(class APlayerController* NewPlayer);
	void KillPlayer(class ABP_FirstPersonCharacter_cLeon_Character_C* FirstpersonCharacter, class ABP_FirstPersonPlayerState_Online_cLeon_C* SourcePlayerState);
	void ModComplete();
	void ReceiveBeginPlay();
	void RemoveGamePlayer(bool IsLogout, class AController* Controller);
	void RoleTeleportDouble_1();
	void RoleTeleportDouble_2();
	void RoleTeleportSurvivor(bool BodyVisibility);
	void SetCheckAnswersTime(int32 CheckAnswersTime_0);
	void SetFoundTarget();
	void SetGameModeIndex(int32 GameModeIndex_0);
	void SetGameTime(int32 TimerDefault_0);
	void SetHunterWaitTime(int32 HunterWaitTime_0);
	void SetMapIndex(int32 MapIndex);
	void SetMaxHunterNum(int32 MaxHunterNum_0);
	void SetRole_Basic_();
	void SetRole_Double_();
	void StartCheckAnswers(bool IsHunterWin);
	void StartGameCheck();
	void SurvivorToHunter(class ABP_PlayerController_cLeon_C* TargetController);
	void TeleportHunter();
	void TeleportLobby();
	void TimerMinus();
	void TimerMinusChickenPhase_1();
	void TimerMinusChickenPhase_2();
	void TimerMinusChickenPhase_3();
	void WinnerCheck();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GameMode_cLeon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GameMode_cLeon_C")
	}
	static class ABP_GameMode_cLeon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_GameMode_cLeon_C>();
	}
};
DUMPER7_ASSERTS_ABP_GameMode_cLeon_C;

SDK_NAMESPACE_END
